# Generated by Django 4.2.5 on 2024-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='portfolio_documents/')),
                ('framework_image', models.ImageField(blank=True, null=True, upload_to='portfolio_images/')),
                ('health_monitoring_document', models.FileField(blank=True, null=True, upload_to='health_documents/')),
                ('health_monitoring_image', models.ImageField(blank=True, null=True, upload_to='health_monitoring_images/')),
            ],
        ),
    ]
