# Generated by Django 4.2.5 on 2024-11-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_description', models.TextField()),
                ('already_given_vaccine_name', models.CharField(max_length=50)),
                ('vaccine_date', models.DateField(blank=True, null=True)),
                ('animal_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='accounts.animal')),
            ],
        ),
    ]
